name: Feature Request
description: Suggest a new feature for the LTSpice to QSpice converter
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide details about what you'd like to see added.
        
  - type: input
    id: feature-title
    attributes:
      label: Feature Title
      description: Brief description of the feature you'd like
      placeholder: "e.g., Support for subcircuit (.sub) files"
    validations:
      required: true
      
  - type: textarea
    id: explanation
    attributes:
      label: Explanation
      description: |
        Please describe:
        • What problem does this solve?
        • How would you like this feature to work?
        • Why is this important for your workflow?
        • Any examples or use cases
        • LTSpice version: X.X.X (used to create schematic)
        • QSpice version: X.X.X (used for viewing/running)
      placeholder: |
        Currently, I can't convert circuits that use subcircuits (.sub files). 
        
        The converter should detect and process .sub files along with the main .asc file...
        
        This would be helpful because many complex circuits rely on subcircuits...
        
        LTSpice version: XVII (17.0.37)
        QSpice version: 24.3.4
    validations:
      required: true